### PR TITLE
Update FGSM.py

### PR DESCRIPTION
**Pull request by OrsonTyphanel93**

### CODE REVIEW

**Comment by SpeakerGuard** [comment]
Hi, thanks for PR. But the current code has no problem:
- In Line 36 of FGSM.py, I have set `self.step_size = epsilon # keep in consistency with PGD`
- In Line  80 and 81, I have set `lower = torch.tensor(lower, device=x.device, dtype=x.dtype).expand_as(x)
        upper = torch.tensor(upper, device=x.device, dtype=x.dtype).expand_as(x)`, 
so lower and upper are not scalar. Using torch.clamp will raise error.

These are used to keep in consistence with PGD. You can see that PGD class inherits from the FGSM class `class PGD(FGSM):`

**Comment by OrsonTyphanel93** [comment]
Thank you ! ! in fact I tried to excuse the code on the @google colab and while instantiating the Pytorch depndances I met an error of the inheriting class :) ( thank you for your remark !!) moreover when you say that FGSM inherits from PGD : are you referring to I-FGSM or BIM ? I am wondering about this iteration of inheritance. 

To solve the BIM problem, PGD involves a truncation operation I understand... :
Another difference with BIM: PGD uses a random initialization for 𝑥f, adding a random noise
to the original sound from a uniform distribution in the interval -𝜖, 𝜖.? 

Thank you very much for your explanations !!!!

**Comment by SpeakerGuard** [comment]
What I mean by inheritance is not from the approach perspective. I only mean we implemented PGD as the inheritance class of FGSM such that PGD can re-use the `def attack_batch()` method of FGSM, allowing us to save some code. Also, PGD overrides the `def attack()` method to deal with its specialness compared to FGSM, e.g., random initialization and truncation operation through `lower` and `upper` (different from that of FGSM). You'd better have a look at our code.

**Comment by OrsonTyphanel93** [comment]
Thanks for the time to exchange, I'll have a look at your code to learn more about it 

and good job for your article

**Pull request closed without merging**
